### ISSUE TITLE
SyntaxError when trying to run

### ISSUE THREAD

**Issue by kostrykin** [hbish/delete-old-tweets#5]
I get this error when running `node index.js -d 2015-01-01`:

`SyntaxError: Unexpected token w in JSON at position 0`

I also had to rename `tweets.js` to `tweet.js` from the downloaded archive.

**Comment by hbish** [comment]
@kostrykin thanks for raising the issue. I will download the latest archive and try and replicate. The format may have changed.

**Comment by rtorr** [comment]
https://github.com/hbish/delete-old-tweets/blob/master/index.js#L79 should be "tweets" not "tweet"

**Comment by hbish** [comment]
@rtorr thanks for that, looks like witter have updated their output. Will update the code and push it out.

**Comment by hbish** [comment]
@kostrykin I have pushed the change, please give it another try.
