### ISSUE TITLE
Error Running

### ISSUE THREAD

**Issue by Minakk22** [hbish/delete-old-tweets#6]
After I run it why does this error appear.

![gambar](https://user-images.githubusercontent.com/110398718/196231916-ec81f10e-bbb7-49f2-899d-9f2379786764.png)

**Comment by yupysec22** [comment]
I renamed tweets.js to tweet.js on data

**Comment by hbish** [comment]
@yupysec22 thanks for raising the issue. I will download the latest archive and try and replicate. The format may have changed.

**Comment by nicolas-t** [comment]
Hello,

you need to modify the first line of tweet.js

```diff
- window.YTD.tweets.part0 = [
+ [
```

**Comment by hbish** [comment]
@nicolas-t @Minakk22 the code replaces the part for you, twitter recently changed the format. Which has just been fixed in the latest version.

Let me know how you go.
